# Generated by Django 3.2.9 on 2021-12-05 01:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=3000, verbose_name='Caption(optional)')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
