# Generated by Django 3.2.9 on 2021-12-05 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0002_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='editor',
            new_name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='default.png', upload_to='images/')),
                ('bio', models.TextField(blank=True, default=' Add Bio', max_length=500)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.profile')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
