# Generated by Django 3.2.9 on 2021-12-05 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_image_editor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='editor',
            new_name='user',
        ),
    ]
