# Generated by Django 3.2.9 on 2021-12-05 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_image_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-upload_date']},
        ),
    ]
