# Generated by Django 3.2.9 on 2021-12-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0008_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='v1638711191/images/default_qu1pfb.png', upload_to='images/'),
        ),
    ]
